"""empty message

Revision ID: d07ce8d0841d
Revises: ef3c0829e44f
Create Date: 2020-05-04 19:41:56.918407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07ce8d0841d'
down_revision = 'ef3c0829e44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artists', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artists', 'seeking_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('artists', 'website',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_unique_constraint(None, 'artists', ['name'])
    op.add_column('artists', sa.Column('genres', sa.ARRAY(sa.String(length=20)), nullable=False))
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String(length=20)), nullable=False))


    op.alter_column('venues', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venues', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('venues', 'website',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'website',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('venues', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('venues', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'genres')
    op.drop_constraint(None, 'artists', type_='unique')
    op.alter_column('artists', 'website',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('artists', 'seeking_description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('artists', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('artists', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
